
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: opshub
    ports:
      - "5432:5432"
    volumes:
      - opshub_db:/var/lib/postgresql/data

volumes:
  opshub_db: